"""
Emit the sensitivity tables for the thesis (Aastha Mehta, AM052) from sweep_results.json.

Columns are exactly the four she asked for, plus the scenario each row belongs to:
    configuration | # solutions | steps to first solution | time to first solution

The engine reports the ITERATION a solution first appears in; the thesis reports STEPS,
the transitions applied to G_0. They differ by one, so steps = iteration - 1.

Usage: python3 gen_sensitivity_tables.py > .../content/explore-sensitivity-tab.tex
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
data = json.load(open(os.path.join(HERE, 'sweep_results.json')))

# Thesis order (tab:case-study-summary), restricted to the swept scenarios.
ORDER = [
    'Mediation',
    'Budget-Constrained Tenant Isolation',
    'Policy-Driven Privilege Separation',
    'CPU Isolation',
    'Multi-Tenant ML Platform',
]
SHORT = {
    'Mediation': 'Mediation',
    'Budget-Constrained Tenant Isolation': r'\makecell[l]{Budget-Constrained\\Tenant Isolation}',
    'Policy-Driven Privilege Separation': r'\makecell[l]{Policy-Driven\\Privilege Separation}',
    'CPU Isolation': 'CPU Isolation',
    'Multi-Tenant ML Platform': r'\makecell[l]{Multi-Tenant\\ML Platform}',
}


def cells(rec):
    it = rec['first_solution_iteration']
    if it is None:
        return '0', '---', '---'
    t = rec['time_to_first_solution']
    return str(rec['solutions']), str(it - 1), (f'{t:.2f}' if t is not None else '---')


def rows(sweep, label, fmt):
    out = []
    for key, rec in data[sweep][label].items():
        sol, steps, t = cells(rec)
        out.append((fmt(key), sol, steps, t))
    return out


print('% Generated by: ~/OSmosis-isosearch/scripts/proc/submarine/gen_sensitivity_tables.py')
print('% Data: ~/OSmosis-isosearch/scripts/proc/submarine/sweep_results.json')
print(f"% Run {data['meta']['generated']}, seed {data['meta']['seed']}. Do not edit by hand.")
print()

# --- Table 1: scoring weights ----------------------------------------------------------
print(r'\begin{table}[htbp]')
print(r'\small\centering')
print(r'\caption{\changetwo{Sensitivity of the search to the scoring weight $\alpha$, with')
print(r'$\beta=1$. \emph{Steps} is the number of transitions applied to $G_0$ to reach the first')
print(r'complete solution, and \emph{Time} is the wall-clock time to reach it, not the duration of')
print(r'the whole run. Every scenario returns the same number of steps at every weight.}}')
print(r'\label{tab:sensitivity-weights}')
print(r'\begin{tabular}{l|r|r|r|r}')
print(r'\hline')
print(r'\textbf{Case Study} & $\mathbf{\alpha}$ & \textbf{\# Sol.} & \textbf{Steps} &'
      r' \textbf{\makecell{Time\\(s)}} \\')
print(r'\hline')
for label in ORDER:
    if label not in data['weights']:
        continue
    rs = rows('weights', label, lambda k: k)
    for i, (cfg, sol, steps, t) in enumerate(rs):
        name = SHORT[label] if i == 0 else ''
        print(f'{name} & {cfg} & {sol} & {steps} & {t} \\\\')
    print(r'\hline')
print(r'\end{tabular}')
print(r'\end{table}')
print()

# --- Table 2: beam width and depth -----------------------------------------------------
print(r'\begin{table}[htbp]')
print(r'\small\centering')
print(r'\caption{\changetwo{Sensitivity of the search to beam width (depth held at each')
print(r"scenario's default) and to the depth bound (beam width held at its default). Columns are as")
print(r'in \autoref{tab:sensitivity-weights}. A dash means no solution was found within that budget.')
print(r'Steps to the first solution never vary; the number of solutions and the time to reach the')
print(r'first one do.}}')
print(r'\label{tab:sensitivity-beam-depth}')
print(r'\begin{tabular}{l|l|r|r|r}')
print(r'\hline')
print(r'\textbf{Case Study} & \textbf{Config.} & \textbf{\# Sol.} & \textbf{Steps} &'
      r' \textbf{\makecell{Time\\(s)}} \\')
print(r'\hline')
for label in ORDER:
    rs = (rows('beam_width', label, lambda k: f'width {k}')
          + rows('depth', label, lambda k: f'depth {k}'))
    for i, (cfg, sol, steps, t) in enumerate(rs):
        name = SHORT[label] if i == 0 else ''
        print(f'{name} & {cfg} & {sol} & {steps} & {t} \\\\')
    print(r'\hline')
print(r'\end{tabular}')
print(r'\end{table}')
