#pragma once    
    
#define CONFIG_LIBSEL4DEBUG_ALLOC_BUFFER_ENTRIES  0    
#define CONFIG_LIBSEL4DEBUG_FUNCTION_INSTRUMENTATION_NONE  1    
/* disabled: CONFIG_LIBSEL4DEBUG_FUNCTION_INSTRUMENTATION_TRACE */    
/* disabled: CONFIG_LIBSEL4DEBUG_FUNCTION_INSTRUMENTATION_BACKTRACE */    
#define CONFIG_LIB_SEL4_DEBUG_FUNCTION_INSTRUMENTAITON  none   
